Refactor obs-portable launcher; more robust and happy shellcheck

diff --git a/builder/obs-portable b/builder/obs-portable
--- a/builder/obs-portable
+++ b/builder/obs-portable
@@ -14,7 +14,11 @@ else
 fi
 
 PORTABLE_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
-export LD_LIBRARY_PATH="${PORTABLE_DIR}/bin/64bit:${PORTABLE_DIR}/obs-plugins/64bit:${PORTABLE_DIR}/data/obs-scripting/64bit:${PORTABLE_DIR}/cef:${LD_LIBRARY_PATH}"
+export LD_LIBRARY_PATH="${PORTABLE_DIR}/bin/64bit":"${PORTABLE_DIR}/obs-plugins/64bit":"${PORTABLE_DIR}/data/obs-scripting/64bit":"${PORTABLE_DIR}/cef":"${PORTABLE_DIR}/lib"${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
 
-cd "${PORTABLE_DIR}/bin/64bit"
-exec ./obs --portable ${@}
+if cd "${PORTABLE_DIR}/bin/64bit"; then
+    exec ./obs --portable "${@}"
+else
+    echo "ERROR! Could not change directory to ${PORTABLE_DIR}/bin/64bit."
+    exit 1
+fi
